### ISSUE TITLE
❌ [BUG] When schedule dropdown is vertically resized b/c of short screen, give visual cue to user to scroll

### ISSUE THREAD

**Issue by chrismejia** [SLB-Pizza/radio-pizza#30]

**Comment by chrismejia** [comment]
This bug also affects mobile screens because many are <768px tall.

**Comment by richdacuban** [comment]
@chrismejia Colorful scrollbar? https://www.npmjs.com/package/react-scrollbars-custom

**Comment by chrismejia** [comment]
Schedule dropdown is fine in current state.

If time remains, this may be revisited.
